title: Hello, world! I'm Orvi
description: > A personal Blog. Love to analyze football and write code.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://orvi2014.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Orvi Das # add your name
author-img: orvi.jpg # add your photo
about-author: Javascript,Python enthunistic| CA,HackerRank |Play Chess |Analyze Football | Hardcore Pink Floyd Fan 	&#x1F493 	&#x1F493 	&#x1F493 	&#x1F493 # add description
twitter: # add your Twitter handle
facebook: dipodijontu # add your Facebook handle
github: orvi2014 # add your Github handle
linkedin: # add your Linkedin handle
email: das.orvi@yahoo.com # add your Email address

# Disqus


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
