title: Hello, world! I'm Robat Das Orvi
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "orvi2014.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Robat Das Orvi # add your name
author-img: orvi.jpg # add your photo
about-author: # add description
twitter: # add your Twitter handle
facebook: dipodijontu # add your Facebook handle
github: orvi2014 # add your Github handle
linkedin: # add your Linkedin handle
email: das.orvi@yahoo.com # add your Email address

# Disqus


# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
